"""change journal to seedbase

Revision ID: 1c80a26c3149
Revises: a8b66eaec159
Create Date: 2025-03-29 16:48:45.145605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c80a26c3149'
down_revision: Union[str, None] = 'a8b66eaec159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seedbeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('soil_number', sa.Integer(), nullable=False),
    sa.Column('plant_type', sa.String(length=50), nullable=False),
    sa.Column('type_of_soil', sa.String(length=50), nullable=False),
    sa.Column('date_planted', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('date_harvested', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seedbeds_id'), 'seedbeds', ['id'], unique=False)
    op.drop_index('ix_journals_id', table_name='journals')
    op.drop_table('journals')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('plant_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('date_planted', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('type_of_soil', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('date_harvested', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('soil_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='journals_pkey')
    )
    op.create_index('ix_journals_id', 'journals', ['id'], unique=False)
    op.drop_index(op.f('ix_seedbeds_id'), table_name='seedbeds')
    op.drop_table('seedbeds')
    # ### end Alembic commands ###
