"""change seedbed model

Revision ID: 21fe4abb054c
Revises: 1c80a26c3149
Create Date: 2025-03-29 16:58:35.501554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21fe4abb054c'
down_revision: Union[str, None] = '1c80a26c3149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seedbeds', sa.Column('plant_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'seedbeds', 'plants', ['plant_id'], ['id'])
    op.drop_column('seedbeds', 'plant_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seedbeds', sa.Column('plant_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'seedbeds', type_='foreignkey')
    op.drop_column('seedbeds', 'plant_id')
    # ### end Alembic commands ###
