"""add journal table

Revision ID: 423c47845ce6
Revises: 6d11265f2c98
Create Date: 2025-03-29 10:06:04.131202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '423c47845ce6'
down_revision: Union[str, None] = '6d11265f2c98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number_of_seedbed', sa.Integer(), nullable=False),
    sa.Column('plant_type', sa.String(length=50), nullable=False),
    sa.Column('date_planted', sa.String(length=50), nullable=False),
    sa.Column('type_of_soil', sa.String(length=50), nullable=False),
    sa.Column('date_harvested', sa.String(length=50), nullable=False),
    sa.Column('temperature', sa.BigInteger(), nullable=False),
    sa.Column('humidity', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journals_id'), 'journals', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journals_id'), table_name='journals')
    op.drop_table('journals')
    # ### end Alembic commands ###
