"""plants editing

Revision ID: 6d11265f2c98
Revises: e403deaf2eaf
Create Date: 2025-03-29 09:15:13.984611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d11265f2c98'
down_revision: Union[str, None] = 'e403deaf2eaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('plants_plant_type_id_fkey', 'plants', type_='foreignkey')
    op.create_foreign_key(None, 'plants', 'plants_type', ['plant_type_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plants', type_='foreignkey')
    op.create_foreign_key('plants_plant_type_id_fkey', 'plants', 'plants_type', ['plant_type_id'], ['id'])
    # ### end Alembic commands ###
