"""change journal table

Revision ID: a8b66eaec159
Revises: c6e8958df695
Create Date: 2025-03-29 16:33:49.216590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8b66eaec159'
down_revision: Union[str, None] = 'c6e8958df695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journals', 'light_level')
    op.drop_column('journals', 'air_temperature')
    op.drop_column('journals', 'air_humidity')
    op.drop_column('journals', 'water_temperature')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journals', sa.Column('water_temperature', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('journals', sa.Column('air_humidity', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('journals', sa.Column('air_temperature', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('journals', sa.Column('light_level', sa.BIGINT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
