"""change journal table

Revision ID: af0fbf13fc38
Revises: cb719fbe3a0c
Create Date: 2025-03-29 10:29:52.393709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af0fbf13fc38'
down_revision: Union[str, None] = 'cb719fbe3a0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('journals', 'date_planted',
        existing_type=sa.VARCHAR(length=50),
        type_=sa.DateTime(),
        existing_nullable=False,
        postgresql_using="date_harvested::timestamp without time zone")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('journals', 'date_planted',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
