"""records table update to float

Revision ID: b4aca4f66c19
Revises: d5d3ec3420a7
Create Date: 2025-03-29 22:09:34.198685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4aca4f66c19'
down_revision: Union[str, None] = 'd5d3ec3420a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('records', 'water_temperature',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('records', 'air_temperature',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('records', 'air_humidity',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('records', 'light_level',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('records', 'height_plant',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('records', 'height_plant',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('records', 'light_level',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('records', 'air_humidity',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('records', 'air_temperature',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('records', 'water_temperature',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
