"""changed telegram integration3

Revision ID: ca056a3676f6
Revises: 6d480d86cf16
Create Date: 2025-03-30 02:52:53.613696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca056a3676f6'
down_revision: Union[str, None] = '6d480d86cf16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_integration',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_integration_id'), 'telegram_integration', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_integration_id'), table_name='telegram_integration')
    op.drop_table('telegram_integration')
    # ### end Alembic commands ###
