"""add records table

Revision ID: d5d3ec3420a7
Revises: 19cdba1ab605
Create Date: 2025-03-29 17:57:35.024318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5d3ec3420a7'
down_revision: Union[str, None] = '19cdba1ab605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('soilId', sa.Integer(), nullable=False),
    sa.Column('photo_link', sa.String(length=255), nullable=False),
    sa.Column('water_temperature', sa.BigInteger(), nullable=False),
    sa.Column('air_temperature', sa.BigInteger(), nullable=False),
    sa.Column('air_humidity', sa.BigInteger(), nullable=False),
    sa.Column('light_level', sa.BigInteger(), nullable=False),
    sa.Column('height_plant', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['soilId'], ['seedbeds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_records_id'), 'records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_records_id'), table_name='records')
    op.drop_table('records')
    # ### end Alembic commands ###
